### ISSUE TITLE
Can you provide a license for this?

### ISSUE THREAD

**Issue by binbalenci** [Scarygami/scary-cookie#1]

**Comment by Scarygami** [comment]
The code is licensed under Apache 2.0 

https://github.com/Scarygami/scary-cookie/blob/master/LICENSE

**Comment by binbalenci** [comment]
Hi @Scarygami, it seems that the repository does not recognize the `LICENSE` file. Can you link the repo to the license?

**Comment by Scarygami** [comment]
License should be correctly displayed now.
